name: barcode_scan
description: A flutter plugin for scanning 2D barcodes and QRCodes via camera.
version: 3.0.4
homepage: https://github.com/mintware-de/flutter_barcode_reader

environment:
  sdk: ">=2.13.0 <4.0.0"

dependencies:
  protobuf: 3.1.0
  flutter:
    sdk: flutter

dev_dependencies:


flutter:
  plugin:
    androidPackage: de.mintware.barcode_scan
    pluginClass: BarcodeScanPlugin