name: barcode_scan
description: A flutter plugin for scanning 2D barcodes and QRCodes via camera.
version: 3.0.5
homepage: https://github.com/mintware-de/flutter_barcode_reader

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  protobuf: 6.0.0
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
  plugin:
    platforms:
      android:
        package: de.mintware.barcode_scan
        pluginClass: BarcodeScanPlugin
      ios:
        pluginClass: BarcodeScanPlugin
